apiVersion: v1
kind: Pod
metadata:
  name: go-app
  namespace: vault
  annotations:
    vault.hashicorp.com/tls-skip-verify: "true"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "vault-role"
    vault.hashicorp.com/agent-inject-secret-app.txt: "kv-v2/fakeapp/mysecret"
  labels:
    app: go-app # Add this label to match the service selector
spec:
  serviceAccountName: vault-sa
  containers:
    - name: go-app
      image: mahi2029/go-docker-app:go-docker-app
      ports:
        - containerPort: 9090
      env:
        - name: VAULT_SECRET_PATH
          value: "/vault/secrets/app.txt"
